### ISSUE TITLE
Major Refactor

### ISSUE THREAD

**Issue by jtimberman** [sous-chefs/ossec#46]
This cookbook needs a fairly major refactoring. Here are some of the things that need to be done.
- [x]  Use upstream package repositories and install the latest version (2.8.2) (addresses #39, #38, #31, #44)
- [x] Use attribute-driven configuration (addresses my comment in #31)
- [ ] Use Chef 12's partial search (addresses #34)
- [ ] Add ChefSpec test coverage for platform differences in conditional branching (#35)
- [ ] Add Serverspec test coverage for post-convergence verification (#36)

This will result in a major version update for this cookbook.

**Comment by jblaine** [comment]
Your first checkbox should target 2.8.2 due to a vulnerability fixed ~last week: http://www.ossec.net/?p=1198

**Comment by jtimberman** [comment]
Updated, thanks!

**Comment by brianhays** [comment]
I have added a yum-atomic cookbook to the supermarket (https://supermarket.chef.io/cookbooks/yum-atomic) that will provide the RPM packages for OSSEC as described here: http://www.ossec.net/?page_id=19 ... also relates to issue #44

**Comment by chewi** [comment]
I was literally going to put my packages pull request up today though I ran out of time before leaving work. I haven't tested any RHEL/Fedora platforms other than CentOS so this might be beneficial. I did add a clause for openSUSE though. I'll see what I can do with this later.

**Comment by chewi** [comment]
Now that I've done the installation from packages, I'm working on the attribute-driven configuration. Converting attributes to XML isn't much fun but I've turned to the Gyoku gem for help.

**Comment by chewi** [comment]
That's the attribute-driven configuration done. Please see #47 and #53.

**Comment by virtadpt** [comment]
I'd love to give this a try on some of my test boxen. :+1:

**Comment by boldandbusted** [comment]
Hey there! Really looking forward to having the ability to use this cookbook with the OSSEC 'official' binary repositories. :) Is there anything we can do to help you?

**Comment by chewi** [comment]
@boldandbusted, I've already done that. Trying it out and leaving feedback would be most helpful.

**Comment by rambler** [comment]
I've been trying the cookbook and I'm running into some issues. What's the right way to provide feedback? I can create more issues here if that would be valuable. Here are the first issues:

1. The ossec user is referenced in client.rb, but doesn't exist. Should we create it within this cookbook or document that the user needs to be created by a wrapper?

2. The server search doesn't seem to work. On my setup I printed it (hack debugging) and it also doesn't work using knife search, so this may be a bug in chef search. Changing the form from "a AND NOT b AND NOT c" to "a AND NOT (b OR c)" seems to fix it.

**Comment by tas50** [comment]
Fixing this cookbook is on my mind, but it's sitting pretty far in the backlog of work to do. It's going to require some significant coding and testing to get it right vs. just adding more attributes to the mess. I'm not saying it won't happen ever, but it'll be a while at the current pace. Help from the community to rethink how we might refactor this cookbook with resources would be great. Bug fixes to at least make the current version functional would also be appreciated.

**Comment by tas50** [comment]
Things have been refactored pretty heavily at this point. We have attribute based configs and source installs have been removed in favor of package installs. This has greatly simplified and improved things.
